web:
  build: .
  ports:
    - '3000:3000'
    - '4000:4000'
  working_dir: /usr/src/app
  command: mv /var/tmp/backend/node_modules /usr/src/app && mv /var/tmp/frontend/node_modules /usr/src/app/frontend
  volumes:
    - ./:/usr/src/app
  links:
    - mongodb

mongodb:
  image: mongo
  volumes:
    - ./tools/backup:/usr/dump
  ports:
    - '27017:27017'