web:
  build: .
  command: sh -c 'pwd npm run build-and-start; npm run start'
  ports:
    - '3000:3000'
    - '4000:4000'
  working_dir: /usr/src/app
  volumes:
    - ./:/usr/src/app
  links:
    - mongodb

mongodb:
  image: mongo
  ports:
    - '27017:27017'